name: Lucia Data publish pipeline
run-name: ${{ github.actor }} run cd for Lucia Data 🚀
on:
  push:
    branches: [main]

jobs:
  data-publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Log in to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
          DOCKER_HUB_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
        run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      - name: build docker
        run: docker build -t ${{secrets.DOCKER_HUB_USERNAME}}/lucia-data .
      - name: publish docker
        run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/lucia-data
      - run: echo "🍏 This job's status is ${{ job.status }}."
